### ISSUE TITLE
Logo-Abstimmung

### ISSUE THREAD

**Issue by katrinleinweber** [ffbsee/ffbsee-grafik#1]
Bitte Logovorschläge hier einstellen: 1 Logo pro Kommentar/Antwort. Die Abstimmung soll mittels der [neuen Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) erfolgen. Bitte nur :+1: benutzen, damit das Auszählen einfach bleibt. Aber dafür gerne mehrere Vorschläge :+1:-en.

**Comment by katrinleinweber** [comment]
[![ffbsee](https://cloud.githubusercontent.com/assets/9948149/13898108/1d10bd90-edc8-11e5-80f0-1cc05ed0fd67.png)](https://github.com/ffbsee/Grafik/blob/master/Logo_Entw%C3%BCrfe/vorschlag_01_%28l3d%29.svg)

**Comment by katrinleinweber** [comment]
@kr0l Die anderen SVGs sind irgendwie zerhackt. Stellt du deinen zweiten und talvis Vorschläge bitte noch hier ein?

**Comment by kr0l** [comment]
Ich habs immer mit inkscape bearbeitet, habe aber vergessen die größe anzupassen, deshalb hatten andere Programme immer Probleme. 
LG 
Kr0l

Am 19. März 2016 11:51:41 MEZ, schrieb Katrin Leinweber <notifications@github.com>:
>@kr0l Die anderen SVGs sind irgendwie zerhackt. Stellt du deinen
>zweiten und talvis Vorschläge bitte noch hier ein?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ffbsee/Grafik/issues/1#issuecomment-198682122

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by DO1JLR** [comment]
**Vorschlag #02:**
![vorschlag_02_ talvi](https://cloud.githubusercontent.com/assets/16953664/13900061/ba39be66-edfd-11e5-95b9-709e1dad5c5e.png)

**Comment by DO1JLR** [comment]
**Vorschlag #03**
![vorschlag_03_ talvi](https://cloud.githubusercontent.com/assets/16953664/13900069/0615fd4a-edfe-11e5-9915-9fec984222ca.png)

**Comment by DO1JLR** [comment]
**Vorschlag #04**
![vorschlag_04_ kr0l](https://cloud.githubusercontent.com/assets/16953664/13900079/4a4e3644-edfe-11e5-91b4-307bf4ad5661.png)

**Comment by DO1JLR** [comment]
**Vorschlag #05**
![vorschlag_05_ kr0l](https://cloud.githubusercontent.com/assets/16953664/13900082/59e781fa-edfe-11e5-9882-a5b79eeba31e.png)

**Comment by DO1JLR** [comment]
**Vorschlag #06**
![vorschlag_06_ kr0l](https://cloud.githubusercontent.com/assets/16953664/13900106/c2f24ff4-edfe-11e5-94ee-3b4c65efa52c.png)

**Comment by DO1JLR** [comment]
**Vorschlag #07**

![vorschlag_07_ kr0l](https://cloud.githubusercontent.com/assets/16953664/13900084/6a1a14a2-edfe-11e5-9bc6-c13090ac5c8a.png)

**Comment by DO1JLR** [comment]
**Vorschlag #08**
![vorschlag_08_ yasemin _](https://cloud.githubusercontent.com/assets/16953664/13900125/00b46aca-edff-11e5-8d50-681b276abfa6.png)

**Comment by DO1JLR** [comment]
**Vorschlag #09**
![vorschlag_09_ yasemin _](https://cloud.githubusercontent.com/assets/16953664/13900128/12e43234-edff-11e5-9497-c46d5e29a089.png)

**Comment by 205er** [comment]
**Vorschlag #10**
![vorschlag_10_ byt3 _](https://cloud.githubusercontent.com/assets/14996169/13903972/7fc7f188-ee90-11e5-8f02-69429b88d157.png)

Basiert auf #8, allerdings mit Verwendung der "offiziellen" Freifunk-Farben und kleineren Änderungen bei der Anordnung und Farbgebung der Objekte

**Comment by DO1JLR** [comment]
![screenshot 56](https://cloud.githubusercontent.com/assets/16953664/14251255/64efbd34-fa82-11e5-95a7-ff16a77ef9c9.png)

Ein weiterer Vorschlag, der vor ein paar Stunden aufgetaucht ist

**Comment by DO1JLR** [comment]
![screenshot 56](https://cloud.githubusercontent.com/assets/16953664/14251387/1413ace4-fa83-11e5-8d95-a6e5e3bdfa13.png)
Und hier hab ich mal eine andere Schrift genommen.

**Comment by DO1JLR** [comment]
![screenshot 60](https://cloud.githubusercontent.com/assets/16953664/14251517/be20cd16-fa83-11e5-9ddc-bbe6d1f1fa1c.png)
Noch ein Vorschlag, der aufgetaucht ist...

**Comment by DO1JLR** [comment]
![screenshot 59](https://cloud.githubusercontent.com/assets/16953664/14251543/d39fea0a-fa83-11e5-8a10-2238bf7e10a1.png)
^^

**Comment by DO1JLR** [comment]
**Die Abstimmung ist vorbei:**
**# 1. Platz: Vorschlag #08**
![vorschlag_08_ yasemin _](https://cloud.githubusercontent.com/assets/16953664/13900125/00b46aca-edff-11e5-8d50-681b276abfa6.png)
**2. Platz: Vorschlag #03**
![vorschlag_03_ talvi](https://cloud.githubusercontent.com/assets/16953664/13900069/0615fd4a-edfe-11e5-9915-9fec984222ca.png)

**3. Platz:**
![screenshot 60](https://cloud.githubusercontent.com/assets/16953664/14251517/be20cd16-fa83-11e5-9ddc-bbe6d1f1fa1c.png)
