### ISSUE TITLE
umleiten: ffbsee.de/router auf https://ffbsee.de/doku.php?id=hardware:router

### ISSUE THREAD

**Issue by katrinleinweber** [ffbsee/ffbsee-grafik#3]
Auf https://github.com/ffbsee/Grafik/blob/master/propaganda/flyer1/ffbsee_flyer1-rueckseite.svg wird erstere kurz-URL benutzt. IMHO sollte das beibehalten werden, aber umgeleitet, anstatt die lange, korrekte URL auf den Flyer aufzuführen.

**Comment by katrinleinweber** [comment]
PS: ffbsee.de/router-flashen auf https://ffbsee.de/doku.php?id=anleitungen:router-flashen ebenso ;-)

**Comment by DO1JLR** [comment]
done

**Comment by L3Dokt0r** [comment]
cat .htaccess
RewriteEngine On
RewriteRule ^index.php/doku.php https://www.freifunk-bodensee.net/doku.php [R=301,L]
RewriteRule ^index.php/home/doku.php https://www.freifunk-bodensee.net/doku.php [R=301,L]
RewriteRule ^impressum https://www.freifunk-bodensee.net/doku.php?id=impressum [R=301,L]
RewriteRule ^router https://freifunk-bodensee.net/doku.php?id=hardware:router
RewriteRule ^router-flashen https://freifunk-bodensee.net/doku.php?id=anleitungen:router-flashen
